### ISSUE TITLE
If the Taskbar is set to automatically hide, the program won't work properly.

### ISSUE THREAD

**Issue by Shelley-the-BeSt-first-character** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#16] opened 2021-11-01 18:57 UTC
Hi, so basically when "Automatically hide the taskbar" is enabled is Settings > Personalization > Taskbar > Taskbar behaviors, when normally dragging a file the taskbar doesn't pop-up, so I have to press the Windows key on my keyboard. However, if you opened the taskbar with the Windows key (thus also the Start Menu), the program won't simulate the Win+T combo. I'd be so grateful, but if you can't, that's also fine I guess. Thanks in advance!

**Comment by HerMajestyDrMona** [comment] 2021-11-01 20:21
Hi. Thanks for your feedback.

I am not sure what I do wrong, but the taskbar shows up when I'm dragging the file at the bottom of the screen. From what I understood, when you have "Automatically hide the taskbar" option enabled, the Taskbar doesn't show up for you? That's strange.

What is very strange, I recorded a video: https://www.youtube.com/watch?v=2H6sWMcxBTI

_**Pinning apps to the taskbar by drag-and-drop is already possible in Windows 11 build 22000.282. When option "Automatically hide the taskbar" is enabled, and Windows11DragAndDropToTaskbarFix is running - the taskbar window crashes. While it's restarting, for a short while it's possible to "Pin to Taskbar". This means, that people who are claiming that "Microsoft has fully rewritten the taskbar, that's why this feature is not available" are lying. This option was disabled on purpose. The taskbar has not been fully rewritten / re-made.**_

So all this bullshit from people claiming that the taskbar was fully rewritten, that's why it doesn't work - are lies.

**Comment by HerMajestyDrMona** [comment] 2021-11-01 20:34
@Shelley-the-BeSt-first-character 

Could you please try to tweak the following variable?

```//For how long (in milliseconds) should the mouse be hovered over the same icon
//on taskbar in order to restore its window.
HowLongKeepMouseOverAppIconBeforeRestoringWindowMilliseconds=200```

Please change it to 1000-2000 as first. Possibly when we give a little bit more time for the taskbar to show up, it won't crash?

**Comment by Shelley-the-BeSt-first-character** [comment] 2021-11-02 16:32
Hmm, strange. It seems like the taskbar only pops up only when I hover the mouse over specific areas? This makes no sense, it didn't happen on Windows 10... I mean, I guess I can get USED to those areas soo I guess thank you?

**Comment by HerMajestyDrMona** [comment] 2021-11-02 16:52
I noticed that it pops up when you hover the mouse over the area where icons are supposed to be. It works the same way with Windows11Drag...blablabla fix not running. So I guess there's no issue in the program itself at the moment. Except these weird crashes that I had yesterday, and then was unable to reproduce after the reboot.

**Comment by HerMajestyDrMona** [comment] 2021-11-03 13:43
Closing this issue for now as it seem to work fine.

**Closed by HerMajestyDrMona** 2021-11-03 13:43 UTC
