### ISSUE TITLE
Disappointed about no pinning apps support

### ISSUE THREAD

**Issue by AndnixSH** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#49] opened 2022-01-12 21:09 UTC
I'm disappointed that the readme stated that the program does not support pinning apps to the taskbar using the drag and drop gesture. But the thing is, I'm using portable apps that require a separate exe launcher so I have no way to pin it. Pinning the running apps is not a solution, portable mode won't work correctly if launched directly

Can you look into it? There must be a way

**Comment by HerMajestyDrMona** [comment] 2022-01-13 14:52
The readme is a bit misleading. It's not like I intentionally didn't add the pinning apps support. I have tried it at least 3 times. The problem is, that all the methods that I read about / tested don't seem to work on Windows 11 for all files. I managed to pin executables, but no other files which were the most needed thing for users. From what I remember, pinning .lnk shortcuts with custom arguments resulted in pinning the .exe directly, so it was all lost.

Executables can be pinned directly using the right click -> "Pin to taskbar" option. [Example](https://www.thewindowsclub.com/how-to-pin-any-app-to-the-taskbar-in-windows-11).

Are you sure that this method doesn't work for you? You could navigate to the folder where your Launcher .exe is, click on it with the right mouse click and "Pin to taskbar" from the list. That should do exactly the same thing as dragging and dropping the program to the taskbar in previous versions of Windows.

Please let me know exactly what you're doing to pin it. Maybe we can find some unrelated to this program solution.

**Comment by AndnixSH** [comment] 2022-01-13 16:01
Ahhh my bad, I completely missed "Pin to taskbar" option under "Show more options". I never used it until now, since I pin via drag and drop since Win7. That solved my problem

So good to close this issue or?

**Comment by HerMajestyDrMona** [comment] 2022-01-13 18:14
Thanks for confirmation that it works now :)

I believe that we can close this issue, as there's nothing else I can do with pinning apps support. I mean, I could add it for .exe files, but for users who could pin other files before it would be even more confusing. So I believe it's better not to add it at all than add it "partially" working.

**Closed by HerMajestyDrMona** 2022-01-13 18:14 UTC
